version: 2.1

jobs:
  build:
    docker: 
    - image: cimg/ruby:3.0.1-node
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install --path ~/.cache/bundle
      - save_cache:
          key: bundle-{{.Branch}}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/bundle
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # - run:
      #     name: Setup database
      #     command: |
      #       bundle exec rake db:create
      #       bundle exec rake db:schema:load
      # - run:
      #     name: Run tests
      #     command: bundle exec rspec
      - run:
          name: Check code style
          command: bundle exec rubocop
